
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/CircleCI

    steps:
      - checkout


  testPython:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: run python tests
          command: python -m unittest src/test/python/CircleCI_POC/test_python.py

  testJVM:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          name: run java/scala tests
          command: mvn package